### ISSUE TITLE
ImportError: No module named geeknote.out

### ISSUE THREAD

**Issue by MrMaksimize** [neilagabriel/vim-geeknote#12]
Just trying to get this running in my vim, and when I run 

vim -c Geeknote, I get:

```
Error detected while processing function Vim_GeeknoteToggle:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/MrMaksimize/.vim_runtime/sources_non_forked/vim-geeknote/plugin/vim_geeknote.py", line 4, in <module>
    from explorer import Explorer
  File "/Users/MrMaksimize/.vim_runtime/sources_non_forked/vim-geeknote/plugin/explorer.py", line 5, in <module>
    from view  import *
  File "/Users/MrMaksimize/.vim_runtime/sources_non_forked/vim-geeknote/plugin/view.py", line 4, in <module>
    from enml  import *
  File "/Users/MrMaksimize/.vim_runtime/sources_non_forked/vim-geeknote/plugin/enml.py", line 5, in <module>
    from geeknote.out import *
ImportError: No module named geeknote.out
```

I'm terribly bad at python -- would love to know what's going on.  Thanks!  

Great and SUPER useful project by the way!

**Comment by scottbaron** [comment]
Neilagabriel - when I first installed GEEKNOTE (2 weeks ago) I was able to operate it from the command line. Now I get the following error. 

➜  ~/.vim/bundle/vim-geeknote/syntax   master  geeknote settings
Traceback (most recent call last):
  File "/usr/local/bin/geeknote", line 9, in <module>
    load_entry_point('geeknote==0.2a0', 'console_scripts', 'geeknote')()
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 519, in load_entry_point
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 2630, in load_entry_point
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 2310, in load
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 2316, in resolve
ImportError: No module named geeknote
 ✘ ➜  ~/.vim/bundle/vim-geeknote/syntax   master 

However I am able to run geeknote within vim. Any suggestions on how to debug this. Again thank you very much.
