### ISSUE TITLE
Error detected while processing function Vim_GeeknoteToggle

### ISSUE THREAD

**Issue by vitaly-zdanevich** [neilagabriel/vim-geeknote#34]
I use `Pathogen`. At `~/.vim/bundle/` I cloned repository, opened text file in vim and have typed: 
`:Geeknote`:

```
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.vim/bundle/vim-geeknote/plugin/vim_geeknote.py", line 4, in <module>
    from explorer import Explorer
  File "/home/ubuntu/.vim/bundle/vim-geeknote/plugin/explorer.py", line 4, in <module>
    from view   import *
  File "/home/ubuntu/.vim/bundle/vim-geeknote/plugin/view.py", line 4, in <module>
    from enml  import *
  File "/home/ubuntu/.vim/bundle/vim-geeknote/plugin/enml.py", line 5, in <module>
    from geeknote.out    import *
ImportError: No module named geeknote.out
```

I have installed `vim` from Ubuntu repository of current LTS (14.04): `7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)`

**Comment by vitaly-zdanevich** [comment]
Sorry at this machine Geeknote was not installed...
