### ISSUE TITLE
Unable to open file in Neovim 0.1.7

### ISSUE THREAD

**Issue by jumbosushi** [neilagabriel/vim-geeknote#40]
Thanks for a great plugin!

I've been able to open file tree, but neovim errors time everytime I try to open a file.
Any idea what's causing it?

```
Neovim version: 0.1.7
Geeknote Version: 2.0.12

Error detected while processing function Vim_GeeknoteActivateNode[4]..provider#python#Call:                                                                                
line   18:                                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                         
  File "<string>", line 2, in <module>                                                                                                                                     
 
 File "/home/atsushi/.config/nvim/plugged/vim-geeknote/plugin/vim_geeknote.py", line 35, in GeeknoteActivateNode                                                          
    explorer.activateNode(vim.current.line)                                                                                                                                
  File "/home/atsushi/.config/nvim/plugged/vim-geeknote/plugin/explorer.py", line 374, in activateNode                                                                     
    node.activate()                                                                                                                                                        
  File "/home/atsushi/.config/nvim/plugged/vim-geeknote/plugin/explorer.py", line 256, in activate                                                                         
    GeeknoteOpenNote(self.note)                                                                                                                                            
  File "/home/atsushi/.config/nvim/plugged/vim-geeknote/plugin/view.py", line 105, in GeeknoteOpenNote                                                                     
    isPrevUsable = GeeknoteIsWindowUsable(prevWin)                                                                                                                         
  File "/home/atsushi/.config/nvim/plugged/vim-geeknote/plugin/view.py", line 218, in GeeknoteIsWindowUsable                                                               
    buftype = getBufferVariable(bnum, 'buftype')                                                                                                                           
  File "/home/atsushi/.config/nvim/plugged/vim-geeknote/plugin/utils.py", line 101, in getBufferVariable                                                                   
    return vim.buffers[bnum].options[var]                                                                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/nvim.py", li                                                                                                     
Press ENTER or type command to continue     
```

**Comment by nkgm** [comment]
Exact same issue in Vim 8.0

**Comment by josswright** [comment]
Same problem here -- has anyone found a solution to this?

NVIM v0.2.2 under Arch Linux.

**Comment by Kelvin-Ng** [comment]
Exactly the same issue here.

Also NVIM v0.2.2 under Arch Linux.

**Comment by XayOn** [comment]
0.4.0-dev here, same issue.
