### ISSUE TITLE
Can't get it to work in VIM version 8.0.95, Ubuntu 17.04 w/only Python3 support

### ISSUE THREAD

**Issue by isene** [neilagabriel/vim-geeknote#41]
VIM under Ubuntu 17.04 only support Python3. Could you make the needed changes to support Python3?

**Comment by DataThinkMonkey** [comment]
I don't believe Evernote's official SDK supports python3 yet. However, you can compile Vim 8.0 with python2.7. The following worked for me on Debian.

sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev \
  libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
  libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
  python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev git

git clone https://github.com/vim/vim.git

cd vim

./configure --with-tlib=ncurses --with-features=huge \
  --enable-multibyte \
  --enable-pythoninterp=yes \
  --with-python-config-dir=/usr/lib64/python2.7/config \
  --enable-luainterp=yes \
  --enable-perlinterp=yes \
  --enable-cscope --prefix=/usr

make
make install_

**Comment by isene** [comment]
Thanks. Works on Ubuntu 17.04 too :-)

**Comment by isene** [comment]
But I get this in VIM:

> :Geeknote<CR>
> Error detected while processing function Vim_GeeknoteToggle:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/geir/Dropbox/setup/vim/bundle/vim- geeknote/plugin/vim_geeknote.py", line 4, in <module>
    from explorer import Explorer
  File "/home/geir/Dropbox/setup/vim/bundle/vim-geeknote/plugin/explorer.py", line 4, in <module>
    from view   import *
  File "/home/geir/Dropbox/setup/vim/bundle/vim-geeknote/plugin/view.py", line 4, in <module>
    from enml  import *
  File "/home/geir/Dropbox/setup/vim/bundle/vim-geeknote/plugin/enml.py", line 5, in <module>
    from geeknote.out    import *
ImportError: No module named geeknote.out`

I'm using Vizardry for install directly from this git repo.

**Comment by isene** [comment]
I get the above after using Vizardy's :Invoke vim-geeknote.
And I do this: 
   :python import sys; print(sys.version)
And get this: 
   2.7.13 (default, Jan 19 2017, 14:48:08)
   [GCC 6.3.0 20170118]

**Comment by isene** [comment]
Nevermind - got it to work (didn't have a real working geeknote in place)
