### ISSUE TITLE
Trying to run under Windows 7 64-bit

### ISSUE THREAD

**Issue by freeo** [neilagabriel/vim-geeknote#8]
I didn't see Windows support written anywhere, but I tried nevertheless. Here's my report. It's not really working, judging by these 3 observations:
- The currently open file is filled (overwritten) with the Geeknote buffer when calling `:Geeknote`
- Running `:Geeknote` produces this error:
  ![geeknote_error](https://cloud.githubusercontent.com/assets/3410566/4542996/5e2dac30-4e27-11e4-8ac5-a51dbc2095b5.jpg)
  
  After that, gvim hangs for a while, then it either crashes, or in rare cases works as expected. When I run the command again, vim raises other errors (had 2 different ones, can't reproduce the 1st one):

```
Error detected while processing function Vim_GeeknoteToggle:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Freeo\vimfiles\bundle\vim-geeknote\plugin\vim_geeknote.py", line 4, in <module>
    from explorer          import Explorer
  File "C:\Users\Freeo\vimfiles\bundle\vim-geeknote\plugin\explorer.py", line 5, in <module>
    from view  import *
  File "C:\Users\Freeo\vimfiles\bundle\vim-geeknote\plugin\view.py", line 15, in <module>
    noteStore = geeknote.getNoteStore()
  File "C:\Python27\lib\site-packages\geeknote-0.2a-py2.7.egg\geeknote\geeknote.py", line 117, in getNoteStore
    noteStoreUrl = self.getUserStore().getNoteStoreUrl(self.authToken)
  File "C:\Python27\lib\site-packages\geeknote-0.2a-py2.7.egg\geeknote\gclient.py", line 183, in getNoteStoreUrl
    return self.recv_getNoteStoreUrl()
  File "C:\Python27\lib\site-packages\geeknote-0.2a-py2.7.egg\geeknote\gclient.py", line 210, in recv_getNoteStoreUrl
    raise result.systemException
evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(errorCode=19, rateLimitDuration=942, _message=None)
```
- This popup error is raised as well everytime(!) I close gvim even without running `:Geeknote`, which is particularly annoying.

Vim 7.4.463 64-bit
Python 2.7.8 64-bit
geeknote 5720fea (Sep 22 12:02:09 2014)

**Comment by sumguysr** [comment]
On windows 8.1 64 bit I had different errors and after a little googling discovered it was due to problems with 64 bit python trying to call the 32 bit socket dll. I switched to a 32 bit python and installation went smoothly. I'm still getting an error on startup I'm trying to debug but the core functionality is working
